#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HTMLUI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <title>登录 | 点狮</title>\r\n    <!--STYLESHEET-->\r\n    <!--===================" +
"==============================-->\r\n    <link");

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" href=\"common/img/ico/PointLion.ico\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 363), Tuple.Create("\"", 404)
, Tuple.Create(Tuple.Create("", 370), Tuple.Create<System.Object, System.Int32>(Href("~/Content/common/css/bootstrap.css")
, 370), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 434), Tuple.Create("\"", 471)
, Tuple.Create(Tuple.Create("", 441), Tuple.Create<System.Object, System.Int32>(Href("~/Content/common/css/nifty.css")
, 441), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n   \r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 506), Tuple.Create("\"", 565)
, Tuple.Create(Tuple.Create("", 513), Tuple.Create<System.Object, System.Int32>(Href("~/Content/common/plugins/switchery/switchery.min.css")
, 513), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n\r\n\r\n    <script");

WriteLiteral(" src=\"http://localhost:50532/Content/common/js/demo/nifty-demo.js\"");

WriteLiteral("></script>\r\n    <!--JAVASCRIPT-->\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 715), Tuple.Create("\"", 760)
, Tuple.Create(Tuple.Create("", 721), Tuple.Create<System.Object, System.Int32>(Href("~/Content/common/js/jquery-2.2.4.min.js")
, 721), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 784), Tuple.Create("\"", 829)
, Tuple.Create(Tuple.Create("", 790), Tuple.Create<System.Object, System.Int32>(Href("~/Content/common/plugins/layer/layer.js")
, 790), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 876), Tuple.Create("\"", 918)
, Tuple.Create(Tuple.Create("", 882), Tuple.Create<System.Object, System.Int32>(Href("~/Content/common/js/bootstrap.min.js")
, 882), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 942), Tuple.Create("\"", 980)
, Tuple.Create(Tuple.Create("", 948), Tuple.Create<System.Object, System.Int32>(Href("~/Content/common/js/nifty.min.js")
, 948), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1004), Tuple.Create("\"", 1061)
, Tuple.Create(Tuple.Create("", 1010), Tuple.Create<System.Object, System.Int32>(Href("~/Content/common/plugins/switchery/switchery.min.js")
, 1010), false)
);

WriteLiteral("></script>\r\n\r\n\r\n\r\n</head>\r\n\r\n\r\n<body>\r\n    <div");

WriteLiteral(" id=\"container\"");

WriteLiteral(" class=\"cls-container\"");

WriteLiteral(">\r\n\r\n\r\n        <div");

WriteLiteral(" id=\"bg-overlay\"");

WriteLiteral(" class=\"bg-img\"");

WriteLiteral(" style=\"background-image: url(~/Content/common/img/bg-img/bg-img-oa.jpg)\"");

WriteLiteral("></div>\r\n\r\n\r\n        <div");

WriteLiteral(" class=\"cls-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"cls-content-sm panel\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"mar-ver pad-btm\"");

WriteLiteral(">\r\n                        <h3");

WriteLiteral(" class=\"h4 mar-no\"");

WriteLiteral(">登录</h3>\r\n                        <p");

WriteLiteral(" class=\"text-muted\"");

WriteLiteral(">使用您的帐号密码进行登录</p>\r\n                    </div>\r\n                    <form");

WriteLiteral(" action=\"/HTMLUI/Home/Main\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"username\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"用户名\"");

WriteLiteral(" autofocus>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" name=\"password\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"密码\"");

WriteLiteral(">\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"checkbox pad-btm text-left\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"captcha\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"验证码\"");

WriteLiteral(" style=\"float: left;width: 162px;margin-right: 40px;\"");

WriteLiteral(">\r\n                            <!--    <img alt=\"验证码出错啦~/Content/!\" src=\"admin/lo" +
"gin/img\">-->\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"checkbox pad-btm text-left\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" id=\"demo-form-checkbox\"");

WriteLiteral(" class=\"magic-checkbox\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" for=\"demo-form-checkbox\"");

WriteLiteral(">记住我</label>\r\n                        </div>\r\n                        <button");

WriteLiteral(" class=\"btn btn-primary btn-lg btn-block\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">登&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;录</button>\r\n                    </form>\r\n        " +
"        </div>\r\n\r\n                <div");

WriteLiteral(" class=\"pad-all\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn-link mar-rgt\"");

WriteLiteral(">忘记密码 ?</a>\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn-link mar-lft\"");

WriteLiteral(">注册新账号</a>\r\n\r\n                    <div");

WriteLiteral(" class=\"media pad-top bord-top\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"pad-rgt\"");

WriteLiteral("><i");

WriteLiteral(" class=\"ti-facebook icon-lg text-primary\"");

WriteLiteral("></i></a>\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"pad-rgt\"");

WriteLiteral("><i");

WriteLiteral(" class=\"ti-twitter-alt icon-lg text-info\"");

WriteLiteral("></i></a>\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"pad-rgt\"");

WriteLiteral("><i");

WriteLiteral(" class=\"ti-google icon-lg text-danger\"");

WriteLiteral("></i></a>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"media-body text-left\"");

WriteLiteral(@">
                            其他方式登录
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--===================================================-->



    </div>
    <!--===================================================-->
    <!-- END OF CONTAINER -->
    ");

WriteLiteral("\r\n\r\n</body>\r\n</html>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
